version: '3.8'
services:
  # Servicio para la aplicación Node.js
  nodejs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
        - .:/usr/src/app
    depends_on:
      - mongodb

  # Servicio para la base de datos MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
        - mongodb_data:/data/db

      
volumes:
  mongodb_data: